<?php

use App\Models\Categorization\Group;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

function appInfo()
{
	$jsonString = file_get_contents(config_path('appInfo.json'));
	return json_decode($jsonString, true);
}

function groups()
{
	return Group::with(['categories.subcategories'])->get();
}

function groupArray()
{
	return $groups = [
	    "Electronic Devices" => [
	        "Smartphones" => [
	        	"realme Phones",
				"Samsung Phones",
				"Xiaomi Phones",
				"OPPO Phones",
				"Vivo Phones",
				"Infinix Phones",
				"Motorola Phones",
				"Tecno Phones",
				"Walton Phones",
	        ],
	        "Feature Phone" => [
	        	"Walton Feature Phone",
				"Nokia Feature Phone",
				"Samsung Feature Phone",
				"iMAX Feature Phone",
				"5 Star Feature Phone",
				"Tinmo Feature Phone",
	        ],
	        "Tablets" => [],
	        "Laptops" => [
	        	"Laptops & Notebooks",
				"Gaming Laptops",
				"HP Laptops",
				"Asus Laptops",
				"Dell Laptops",
				"Lenovo Laptops",
				"Walton Laptops",
				"Acer Laptops",
				"MSI Laptop",
	        ],
	        "Desktops" => [
	        	"All-In-One",
				"Gaming Desktops",
	        ],
	        "Gaming Consoles" => [
	        	"PlayStation Consoles",
				"Playstation Games",
				"Playstation Controllers",
				"Nintendo Games",
				"Xbox Games",
				"Other Gaming Consoles",
	        ],
	        "Cameras" => [
	        	"DSLR",
				"Mirrorless",
				"Point & Shoot",
				"Bridge",
				"Car Cameras",
				"Action/Video Cameras",
	        ],
	        "Security Cameras" => [
	        	"IP Security Cameras",
				"IP Security Systems",
				"CCTV Security Cameras",
				"CCTV Security Systems",
	        ],
	    ],
	    "Electronic Accessories" => [
	        "Mobile Accessories" => [],
	        "Audio" => [],
	        "Wearable" => [],
	        "Console Accessories" => [],
	        "Camera Accessories" => [],
	        "Computer Accessories" => [],
	        "Storage" => [],
	        "Printer" => [],
	        "Computer Components" => [],
	        "Network Components" => [],
	        "Software" => [],
	    ],
	    "TV & Home Appliances" => [
	        "Televisions" => [],
	        "Home Audio" => [],
	        "TV Accessories & Video Device" => [],
	        "Large Appliances" => [],
	        "Small Kitchen Appliances" => [],
	        "Cooling & Heating" => [],
	        "Fan" => [],
	        "Vacuums & Floor Care" => [],
	        "Irons & Garment Steamers" => [],
	        "Water Purifiers & Filters" => [],
	    ],
	    "Health & Beauty" => [
	        "Bath & Body" => [],
	        "Beauty Tools" => [],
	        "Fragrances" => [],
	        "Hair Care" => [],
	        "Makeup" => [],
	        "Men's Care" => [],
	        "Personal Care" => [],
	        "Skin Care" => [],
	        "Food Supplements" => [],
	        "Medical Supplies" => [],
	        "Sexual Wellness" => [],
	    ],
	    "Babies & Toys" => [
	        "Mother & Baby" => [],
	        "Feeding" => [],
	        "Diapering & Potty" => [],
	        "Baby Gear" => [],
	        "Baby Personal Care" => [],
	        "Clothing & Accessories" => [],
	        "Nursery" => [],
	        "Toys & Games" => [],
	        "Baby & Toddler Toys" => [],
	        "Remote Control & Vehicles" => [],
	        "Sports & Outdoor Play" => [],
	        "Traditional Games" => [],
	    ],
	    "Groceries & Pets" => [
	        "Beverages" => [],
	        "Choco & Snacks" => [],
	        "Food Staples" => [],
	        "Cooking Ingredients" => [],
	        "Laundry & Household" => [],
	        "Cat" => [],
	        "Dog" => [],
	        "Fish" => [],
	        "Bird" => [],
	        "Small Pet" => [],
	        "Lifestyle Accessories" => [],
	    ],
	    "Home & Lifestyle" => [
	        "Bath" => [],
	        "Bedding" => [],
	        "Decor" => [],
	        "Furniture" => [],
	        "Kitchen & Dining" => [],
	        "Lighting" => [],
	        "Laundry & Cleaning" => [],
	        "Tools" => [],
	        "DIY & Outdoor" => [],
	        "Stationery & Craft" => [],
	        "Media" => [],
	        "Music & Books" => [],
	    ],
	    "Women's Fashion" => [
	        "Sweaters & Cardigans" => [],
	        "Jackets & Coats" => [],
	        "Sarees" => [],
	        "Shalwar Kameez" => [],
	        "Unstitched Fabric" => [],
	        "Kurtis" => [],
	        "Clothing" => [],
	        "Women's Bags" => [],
	        "Shoes" => [],
	        "Accessories" => [],
	        "Lingerie => [], Sleep & Lounge" => [],
	        "Travel & Luggage" => [],
	    ],
	    "Men's Fashion" => [
	        "Jackets & Coats" => [],
	        "Hoodies & Sweatshirts" => [],
	        "Sweaters" => [],
	        "T-Shirts" => [],
	        "Shirts" => [],
	        "Polo Shirts" => [],
	        "Jeans" => [],
	        "Pant" => [],
	        "Men's Bags" => [],
	        "Shoes" => [],
	        "Accessories" => [],
	        "Clothing" => [],
	    ],
	    "Watches & Accessories" => [
	        "Men's Watch" => [],
	        "Women's Watch" => [],
	        "Women's Jewelleries" => [],
	        "Men's Jewelleries" => [],
	        "Fashion Mask" => [],
	        "Men's Belt" => [],
	        "Men's Wallet" => [],
	        "Sunglasses" => [],
	        "Eyeglasses" => [],
	        "Kid's Watch" => [],
	    ],
	    "Sports & Outdoor" => [
	        "Treadmills" => [],
	        "Fitness Accessories" => [],
	        "Dumbbells" => [],
	        "Cycling" => [],
	        "Boxing" => [],
	        "Martial Arts & MMA" => [],
	        "Men Shoes & Clothing" => [],
	        "Outdoor Recreation" => [],
	        "Exercise & Fitness" => [],
	        "Racket Sports" => [],
	        "Team Sports" => [],
	        "Camping & Hiking" => [],
	        "Fanshop" => [],
	    ],
	    "Automotive & Motorbike" => [
	        "Automobile" => [],
	        "Auto Oils & Fluids" => [],
	        "Interior Accessories" => [],
	        "Exterior Accessories" => [],
	        "Exterior Vehicle Care" => [],
	        "Interior Vehicle Care" => [],
	        "Car Electronics Accessories" => [],
	        "Car Audio" => [],
	        "Motorcycle" => [],
	        "Moto Parts & Accessories" => [],
	        "Motorcycle Riding Gear" => [],
	    ],
	    "Food" => [
	        "Protien House" => [],
	        "Vegetables" => [],
	        "Processed Food" => [],
	    ]
	];
}
